name: Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  check-changes:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: git fetch
      - run: git log origin/${{ github.event.pull_request.base.ref }}..


      - name: Setup Go 1.22.x
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: install kubectl-validate
        run: go install sigs.k8s.io/kubectl-validate@latest
        
